spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-auth-service-users-wildcard
          uri: http://user-auth-service:8080
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: user-auth-service-login
          uri: http://user-auth-service:8080
          predicates:
            - Path=/login
            - Method=POST

server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
