spring:
  application:
    name: user-auth-service
  datasource:
    url: jdbc:mysql://localhost:3307/synergy-hub
    username: user
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect