version: '3.8'
services:
  mysql:
    image: mysql:8.3
    container_name: synergy-hub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: synergy-hub
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Example for a backend service (uncomment and adjust as needed)
  user-auth-service:
    build: ../../backend/user-auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/synergy-hub
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data: